language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - cd CatchEmAllFrontEnd
  - npm install -g @angular/cli

script:
  - ng build --prod
  - npm install sonar-scanner
  - sonar-scanner -Dsonar.projectKey=1908-aug19-java_Project2-YinYu-Andres-Howard -Dsonar.organization=carolynrehm-github -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
